### ISSUE TITLE
Feature Request, per Way-Point Velocity Constraints

### ISSUE THREAD

**Issue by EdsterG** [hungpham2511/toppra#10]
Support for per way-point velocity constraints.

**Comment by hungpham2511** [comment]
Is `JointVelocityConstraint` what you are looking for?

**Comment by EdsterG** [comment]
Can I have a different `JointVelocityConstraint` per way-point?

**Comment by hungpham2511** [comment]
That should be possible!

**Comment by hungpham2511** [comment]
I am happy to announce that path-varying joint velocity constraint is now supported. Please take a look at  https://github.com/hungpham2511/toppra/blob/master/toppra/constraint/joint_velocity.py#L42 in the lastest commit on master.

**Comment by mrunaljsarvaiya** [comment]
Could you give an example as to how the `vlim_func` could be constructed for when using a system with DOF > 1 ?
