### ISSUE TITLE
Cartesian acceleration/velocity constraints 

### ISSUE THREAD

**Issue by hungpham2511** [hungpham2511/toppra#101]
**Describe the solution you'd like**
Implementations of Cartesian acceleration/velocity constraints with the C++ API

Now it's possible to implement this using either OpenRAVE or https://github.com/stack-of-tasks/pinocchio Probably we should implement both.

An example interface:
```C++

```

**Comment by thummel42** [comment]
Hey just asking if there is an example python interface that can be ported to cpp for this. Specifically would like to do varying velocity and acceleration constraints.

**Comment by hungpham2511** [comment]
Yes I plan to do this for sometime for unfortunately couldn't find the time for it. It should be a straightforward extension of https://github.com/hungpham2511/toppra/blob/develop/toppra/constraint/linear_second_order.py

**Comment by stevegolton** [comment]
Hi @hungpham2511. I had a go at making a Cartesian velocity constraint class (see listing below). It seems to work just fine using an `fk` implementation based on PyKDL's `ChainFkSolverVel_recursive`, but I'm not sure why I have to square the outputs of the `invdyn` and `constraintg` functions. I'll admit my understanding of the maths is hazy. Is this something like the class you had imagined?

```
class CartesianVelocityConstraint(constraint.SecondOrderConstraint):
    """This class implements a constraint on Cartesian linear and angular velocity of some link in the robot chain.
    """

    def __init__(self, fk, max_linear, max_angular, dof):
        """Initialize the constraint.

        Parameters
        ----------
        fk: (np.ndarray, np.ndarray) -> (linear_vel, angular_vel)
            The "FK" function that receives joint position and velocity as inputs and ouputs
            the linear and angular velocity of some link of the robot.
        max_linear: float
            The max linear velocity allowed for that link.
        max_angular: float
            The max angular velocity allowed for that link.
        dof: int
            The dimension of the joint position.
        """
        super(CartesianVelocityConstraint, self).__init__(self.invdyn, self.constraintf, self.constraintg, dof)
        self.fk = fk
        self.max_linear = max_linear
        self.max_angular = max_angular

    def invdyn(self, q, dq, ddq):
        linear, angular = self.fk(q, dq)
        return np.array([linear**2, angular**2])

    def constraintf(self, q):
        # 2x2 identity matrix
        return np.identity(2)

    def constraintg(self, q):
        return np.array([self.max_linear**2, self.max_angular**2])
```

**Comment by hungpham2511** [comment]
Hi @stevegolton, have you had a look at this [example](https://github.com/hungpham2511/toppra/blob/develop/examples-old/cartesian_accel.py)? By the way, if you have a PR for this feature I will be happy to review and merge it.

**Comment by stevegolton** [comment]
Thanks! I hadn't found that example before, that's really helpful. PR submitted #144.

**Comment by jmirabel** [comment]
For completeness, I see two ways of making velocity limit fit into the constraint model of TOPPRA.
1. limit on the squared S-norm (See #146)
2. limit on individual components that ends up to ` sd^2 < (limit / v_i)^2` where `v_i` is the i-th component of `v = J(q(s)) qdot(s)`

**Comment by jmirabel** [comment]
> I'm not sure why I have to square the outputs of the `invdyn` and `constraintg` functions.

The algo works by solving a bunch of LPs. The variables are `\ddot{s}` and `\dot{s}^2`. Your constraint has to be linear with respect to these variables.
