### ISSUE TITLE
Implement Seidel LP solver in C++

### ISSUE THREAD

**Issue by hungpham2511** [hungpham2511/toppra#109]
The Cython implementation of Seidel LP solver 

https://github.com/hungpham2511/toppra/blob/ba9328cd2f4e0ecb1eb71bba5c98fab78a8b4be6/toppra/solverwrapper/cy_seidel_solverwrapper.pyx#L65

is still the fastest solver for toppra. This solver was very important to achieve sub-millisecond solution time, or, a reasonable time for large and difficult problem.

It will be ideal to implement this in C++, then provide a binding back to the Python API.

**Comment by yy16808** [comment]
How to call  Cython implementation in C++?

**Comment by hungpham2511** [comment]
Hi, I have no idea how to do that, and even if it's possible I doubt it's a good idea.

Bests,

Hung

________________________________

**Comment by xiaodaxia-2008** [comment]
Maybe a re-implementation with cpp is fast enough. Actually I've already done this part after trying several third-party solvers (which are more generous but not fast enough for 2D LP).
