### ISSUE TITLE
Varying joint velocity constraints for cpp

### ISSUE THREAD

**Issue by thummel42** [hungpham2511/toppra#124]
**Is your feature request related to a problem? Please describe.**
Currently the C++ does not seem to support varying joint velocity constraints for the path (velocity per way-point) in the same manner as the python API.

**Describe the solution you'd like**
It would be god to see an example of varying velocity contraints with the C++ implementation or the feature added if the API cannot support it. 

**Describe alternatives you've considered**
Currently my organization uses the library in a python context but our stack is in C++. We would like to migrate this library to C++, however the lack of varying velocity constraints in the C++ implementation is a blocker.

**Comment by thummel42** [comment]
@jmirabel Yup definitely interested

**Comment by jmirabel** [comment]
I realized that it was longer to explain than to implement so I implemented it.

If you could contribute by adding a unit test for this feature, that would be fantastic.
