### ISSUE TITLE
Specify the start and end velocity and acceleration values

### ISSUE THREAD

**Issue by yy16808** [hungpham2511/toppra#131]
Is it possible to specify the start and end velocity and acceleration values？  Which is convenient to connect multiple trajecotries.

**Comment by hungpham2511** [comment]
Yes, it is. You can specify the path velocity at the start and end.

Please note that you need to make sure that the trajectories have the same tangent at the connecting points.

**Comment by zzzbbs** [comment]
> Is it possible to specify the start and end velocity and acceleration values？ Which is convenient to connect multiple trajecotries.

Hello @yy16808 , have you solved this problem? I have questions about this too. Looking forward to your reply!
