### ISSUE TITLE
Interest in updating C++ implementation to leverage IFOPT

### ISSUE THREAD

**Issue by Levi-Armstrong** [hungpham2511/toppra#142]
Hello we recently went through and updated [TrajOpt](https://github.com/ros-industrial-consortium/trajopt_ros) to leverage [IFOPT](https://github.com/ethz-adrl/ifopt) which opened up access to additional solvers and wanted to see if the maintainers have looked at this and if there would be any interest in updating Toppra to leverage this for the C++? It currently supports SNOPT and IPOPT but the TrajOpt includes Gurobi, OSQP and qpOASES which we are looking into pushing to IFOPT.

**Comment by hungpham2511** [comment]
Hi there, that's good to hear. 

toppra currently uses only linear and quadratic solvers internally so I don't think it can leverage much this development.
