### ISSUE TITLE
LP solve efficiency

### ISSUE THREAD

**Issue by SHIXIAOLI022048** [hungpham2511/toppra#170]
Hi,

Here is my question. Now there are three solvers provided for C++ API, is the Seidel solver the fastest one to solve LP problems?

Thanks!

**Comment by hungpham2511** [comment]
In my experience, Seidel solver is the simplest and thus it often is the fastest.

**Comment by SHIXIAOLI022048** [comment]
Thanks a lot!!


------------------------------------------------------------------
发件人：Hung Pham (Phạm Tiến Hùng) ***@***.***>
发送时间：2021年4月25日(星期日) 16:15
收件人：hungpham2511/toppra ***@***.***>
抄　送：史晓立 ***@***.***>; State change ***@***.***>
主　题：Re: [hungpham2511/toppra] LP solve efficiency (#170)

In my experience, Seidel solver is the simplest and thus it often is the fastest.

**Comment by xbaosong** [comment]
The Seidel solver is reported 10 times faster than simplex method for low-dimension LP(< 10).

This is mentioned here: [SDLP](https://github.com/ZJU-FAST-Lab/SDLP)
