### ISSUE TITLE
about compute the reachable set

### ISSUE THREAD

**Issue by fuyu-jia** [hungpham2511/toppra#18]
I tried the function compute_controllable_set(), it works well. When I tried to implement a similar but forward function compute_reachable_set(), it seems that something was wrong. I have forked your repo, and commit my modification, as you can see on [forked_toppra](https://github.com/fuyuhejia/toppra/commits/master)

I really appreciate that if you can help me and point where was wrong when you are free. thank for your time

![20181027_compute_reachable_sets](https://user-images.githubusercontent.com/35056457/47600481-73a15280-d9f4-11e8-867f-c1a94fb1932c.png)

**Comment by hungpham2511** [comment]
@fuyu-guo  I just make some comments on your commits. Please take a look.

**Comment by hungpham2511** [comment]
@fuyu-jia Please close the issue if it has been addressed.
