### ISSUE TITLE
Using a CartesianVelocityNorm constraint in a pure python implementation

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [hungpham2511/toppra#188]
If I were to build the python bindings for `CartesianVelocityNorm`, can I use it as a constraint directly through `toppra.algorithm.TOPPRA` or does it have to be through `toppra.cpp.TOPPRA`?

**Comment by hungpham2511** [comment]
It has to be via the cpp binding I am afraid.

**Comment by mrunaljsarvaiya** [comment]
Thanks! Is there another place I could ask questions btw? I hate to create an issue every time I need to do so
