### ISSUE TITLE
New tag/release request

### ISSUE THREAD

**Issue by hashb** [hungpham2511/toppra#199]
I am trying to use the recently added get times function. Could you create a new release off the latest master branch

**Comment by hungpham2511** [comment]
Hi, sorry the late reply. Sure thing!

**Comment by hungpham2511** [comment]
Actually the latest master code has been released as 0.4.1 quite a while ago. Is that not what you look for?

**Comment by hashb** [comment]
sorry, my bad, I am using develop branch not master. I am interested in PR https://github.com/hungpham2511/toppra/pull/197

**Comment by hungpham2511** [comment]
> sorry, my bad, I am using develop branch not master. I am interested in PR #197

Ah ok. Will do.

**Comment by hashb** [comment]
Thank you for the new release. closing this issue now.

**Comment by hungpham2511** [comment]
> Thank you for the new release. closing this issue now.

Hi @hashb just curious are you using the Python or C++ version of the library?

**Comment by hashb** [comment]
I've been using the python version for a couple of months. I recently switched to the C++ version of the library.
