### ISSUE TITLE
Linear Cartesian move as a constraint

### ISSUE THREAD

**Issue by chen-tianjian** [hungpham2511/toppra#218]
Just wondering if it is possible to formulate the constraints to make the end-effector move in a straight line in Cartesian space (for example, Cartesian velocity direction deviation smaller than a small number)? If so I guess it would be an interesting example.

**Comment by jmirabel** [comment]
TOPPRA does not change the path. It only change the time parametrization. So no, TOPPRA cannot constrain the end effector to move on a straight line.

**Comment by chen-tianjian** [comment]
Thanks for your reply. Correct me if I am wrong, I am thinking about generating joint profile between 2 way points (that is sort of "re-timing"), and properly formulate the constraint (using Jacobian) such that the end-effector velocity follows a straight line between the 2 way points.

**Comment by jmirabel** [comment]
TOPPRA does not modify the geometric path. The joint velocity direction will not be modified. Only its magnitude is. What you ask for is an IK solver and/or a motion planner. This is out of the scope of this repo. 

You can find other open source software to do this. The choice depends on your use case.

Or I don't understand your problem.
