### ISSUE TITLE
C++ version install error 

### ISSUE THREAD

**Issue by zxfever** [hungpham2511/toppra#254]
I follow the instruction mentioned here in the [Readme](https://github.com/hungpham2511/toppra/tree/develop/cpp#readme).

while building(make), the tests subdirectory failed with the multiple following errors

```
error: call of overloaded ‘BoundaryCond(<brace-enclosed initializer list>)’ is ambiguous
```
it seems to be the namespace error, how to fix it?

**Comment by Shihao-Feng-98** [comment]
I face the same problem, can you share your solutions?
