### ISSUE TITLE
Installation error (venv): no module named numpy

### ISSUE THREAD

**Issue by gavanderhoorn** [hungpham2511/toppra#28]
Not sure this is pebcak, so decided to report it.

Following the installation instructions [here](https://hungpham2511.github.io/toppra/installation.html) I ran into the following error while executing the command `pip install -r requirements.txt` in a `virtualenv`:

```
Collecting CVXcanon>=0.0.22 (from cvxpy<1.0.0,>=0.4.11->-r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9e/e6/63eb6e7dca5dcb723429e65b456d0e3638976e63f6696b7eb48fee3a491d/CVXcanon-0.1.1.tar.gz (694kB)
    100% |████████████████████████████████| 696kB 28.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xyDTn9/CVXcanon/setup.py", line 4, in <module>
        import numpy
    ImportError: No module named numpy
```

After manually installing `numpy` first with `pip install numpy`, `pip` was able to continue installing the other requirements.

**Comment by hungpham2511** [comment]
Thanks for reporting. It is strange this happens though, because numpy is already in `requirements.txt`
