### ISSUE TITLE
The optimized path is not optimal

### ISSUE THREAD

**Issue by tjh49** [hungpham2511/toppra#30]
I optimized my path with the velocity and acceleration limits set as shown in the picture below. But I think the path is not optimal, since the max velocity and acceleration of optimized path are much lower than the limits. 
So, is it possible to further optimize the path, so that the max velocity is nearly the limits and the path motion time is least? 

![image](https://user-images.githubusercontent.com/29271612/53283638-661e8e00-3784-11e9-88b0-6ebbe9200fb2.png)

**Comment by tjh49** [comment]
Well, my mistake, bugs in my code. Sorry

**Comment by hungpham2511** [comment]
@tjh49 no worries. Please close the issue though.
