### ISSUE TITLE
TOPPRA for path planning

### ISSUE THREAD

**Issue by JadBatmobile** [hungpham2511/toppra#31]
Im curious about a potential use case of toppra. Say i have a path, parameterized by x, y, and theta. So a vehicle or robot is travelling some arbitrary path in the world, with each point being defined by an x,y coordinate, and a heading of the vehicle theta.

Would toppra work for time parameterizing this path, given that the units of the x,y coordinates are meters, and theta is radians? do the units have to be the same?

thank you

**Comment by hungpham2511** [comment]
Unit should not be a problem, provided that the same unit is used for the constraints. As long as you only have bounds on velocity and acceleration, there should not be any problem.

If you do try to use toppra for that case, I am very interested in knowing how it works out.

Cheers,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JadBatmobile** [comment]
okay cool, i will let you know!!

**Comment by JadBatmobile** [comment]
Hey hung,

when reading the paper, i am abit confused with equation (7).

I dont see how x(i+1) = x(i) + 2(s(i+1)-s(i))*(u(i))

**Comment by hungpham2511** [comment]
I will close this issue. Feel free to open another one if need.
