### ISSUE TITLE
Can I pass in non-zero starting and goal velocity for each DOF? 

### ISSUE THREAD

**Issue by Shentheman** [hungpham2511/toppra#33]
I am wondering whether there is a way to specify the starting and goal positions and velocities for each DOF into functions such as `compute_trajectory` in `scalar_example.py`?

It seems that `0` is always passed in `instance.compute_trajectory(0, 0)`. Is there a way to pass in a list of velocities of all the DOFs into `compute_trajectory`?

**Comment by hungpham2511** [comment]
Hi @Shentheman, sorry for the delay. I must have missed the issue for some reason.

The answer is yes, but since you need to have a fixed geometric path, there is only 1 dof to control the start and end velocity.
