### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by gavanderhoorn** [hungpham2511/toppra#36]
Have you considered releasing this module on pypi?

**Comment by hungpham2511** [comment]
Yes it will be released soon.

**Comment by gavanderhoorn** [comment]
Great. Simplifies installation even more if one can just use a `pip install toppra`.

**Comment by hungpham2511** [comment]
Thank for the suggestion.

**Comment by gavanderhoorn** [comment]
I couldn't find it on pypi. Am I wrong in assuming you closed this because you've released the package on pypi?

**Comment by hungpham2511** [comment]
Yeah I have not published the package to pip yet.
