### ISSUE TITLE
Implementation of the algorithm in C++?

### ISSUE THREAD

**Issue by oPiZiL** [hungpham2511/toppra#43]

**Comment by hungpham2511** [comment]
I don't have any plan to do that in the near future. That said, the main difficulty is that there are no fast LP solvers for small-sized problems in C++, or that I couldn't find any.

**Comment by JadBatmobile** [comment]
Any updates on this topic?

**Comment by pbeeson** [comment]
I know at least one person that HAS done this (and even constrained through
jerk, not just acceleration), but it's not open source.  Perhaps they might
at least be willing to share which c++ solver they used.  I will ping them
to see.

**Comment by JadBatmobile** [comment]
Thank you sir

**Comment by pbeeson** [comment]
It looks like the programmer just rolled his own LP Solver for c++.  If I
hear more about this being licensed or opened, I'll follow-up on this issue.

**Comment by JadTawil-theonly** [comment]
Hey Patrick,

Any updates on this ?

**Comment by pbeeson** [comment]
Looks like the company he did this for is keeping this as private IP for
now.

**Comment by JadTawil-theonly** [comment]
Thank you sir

**Comment by oPiZiL** [comment]
> I don't have any plan to do that in the near future. That said, the main difficulty is that there are no fast LP solvers for small-sized problems in C++, or that I couldn't find any.

How about the glpk

**Comment by EmanueleSiego** [comment]
> > I don't have any plan to do that in the near future. That said, the main difficulty is that there are no fast LP solvers for small-sized problems in C++, or that I couldn't find any.
> 
> How about the glpk

OSQP is a great open-source QP solver that my colleague is testing for his master thesis. I think it can be used for LP too.

**Comment by hungpham2511** [comment]
Yes, both (glpk and osqp) are good solvers. However, since they are designed for problems having much larger sizes than those solved by `toppra`, there will be speed penalties.

**Comment by zhaodong1986** [comment]
maybe could try Mike Hohmeyer's implementation for R. Seidel's LP solver(https://github.com/cgrushko/seidel-lp-solver) and tranlate it with C++

**Comment by jmirabel** [comment]
> I don't have any plan to do that in the near future. That said, the main difficulty is that there are no fast LP solvers for small-sized problems in C++, or that I couldn't find any.

Hello,
In the article, you used qpOASES, which a C++ library. Any reason not to use it in the C++ implementation ?
I am thinking in implementing your algorithm.

**Comment by hungpham2511** [comment]
Sure qpOASES is a really good solver, but it's not specialized to small LP problems. Thus it's unlikely that we would gain any speed benefits from implementing TOPPRA in C++ using qpOASES. I already use qpOASES Python wrapper in this version.

That said, having an interface in C++ is by itself a really nice thing already. Actually I have thought of doing that for a while but unfortunately didn't find the chance to do that.

**Comment by jmirabel** [comment]
My primary goal is the C++ interface. The execution time is not a hard constraint for me.

**Comment by jmirabel** [comment]
We can collaborate on this topic if you have some time for this.

**Comment by hungpham2511** [comment]
In that case I don't see any problem with reimplementing toppra using qpoases as the underlying solver. 

> We can collaborate on this topic if you have some time for this.

That sounds great! Let's do that then.

**Comment by hungpham2511** [comment]
@jmirabel Let's discuss the C++ interface design in this issue: https://github.com/hungpham2511/toppra/issues/82

**Comment by hungpham2511** [comment]
An initial version is released in #100. Thus I will close this issue.
