### ISSUE TITLE
python requirements boken in latest updates

### ISSUE THREAD

**Issue by pbeeson** [hungpham2511/toppra#53]
As of 5/17/2019, the top version of scipy in pip depends on python-3.5.  It's unclear exactly what platform you are targeting as a default working platform, but if you are still shooting for Python 2.7 then you'll want scipy<1.3 in requirements.txt..

**Comment by hungpham2511** [comment]
I have tested toppra on Python 3 and things seem yo work. Can I know the steps you have taken to install?

Btw you can try 'pip install toppra' instead.

Bests,

Hung

________________________________

**Comment by pbeeson** [comment]
It does work for python3.  I got that working eventually.

But I can’t pip install toppra because your latest changes break some
benchmarks tests.  Changes you made prior to the auto scaling feature are
actually more stable than later versions in my testing.
