### ISSUE TITLE
Additional information about the generated trajectory

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [hungpham2511/toppra#61]
Is there a way to determine velocity, acceleration and time information for a specific input waypoint?
For example, a evaluation function (similar to `jnt_traj.eval()`), that instead of taking as an input a time step, takes a waypoint ?

**Comment by hungpham2511** [comment]
Yes this information can be retrieved from the output of the algorithm. In fact the velocities at each waypoint are used to compute the final retimed trajectory.

**Comment by mrunaljsarvaiya** [comment]
Thanks!
