### ISSUE TITLE
Smoothing output joints profile

### ISSUE THREAD

**Issue by EmanueleSiego** [hungpham2511/toppra#76]
Actually topp-ra does not manage jerk constraints on joints or cartesian space. For industrial robots discontinuous joints acceleration leads to high vibrations because of elastic resonances.
On the other hand, filtering output joints profile deforms the nominal trajectory. The idea is to apply a FIR filter to the profile in s-s_dot space. In this way the nominal trajectory won't be deformed and the output joints profile becomes smoother (even if there's no control on the jerk value). I don't know if this solution garantees all set constraints in joints space (i.e. torques constraints).

**Comment by hungpham2511** [comment]
Hi @EmanueleSiego yes you can definitely smoothen the velocity profile before returning the trajectory. 

While velocity and torque constraints might be violated if "significant smoothing" is done, in terms of practical motion planning on industrial robots, I don't think that poses a big problem. In any case, you can think of it as an engineering trade-off that should be selected or tuned for different robot systems.
