### ISSUE TITLE
How to replaced the inv_dyn function provided by openRave with our own

### ISSUE THREAD

**Issue by meihuiZhang** [hungpham2511/toppra#92]
__When I impose the joint torque constraints into the toppra, i want to replaced the inv_dyn function provided by openRave with our own inverse dynamics function. Because my dynamics model contains viscous friction and coulomb friction, to the end, the each joint torque contains the ds item (as shown below).
![joint_torque](https://user-images.githubusercontent.com/61768106/80078615-bd371300-8581-11ea-84f5-223e83754a63.png)
I think that it need another coefficient matrix apart from a(s), b(s) and c(s), but I do not know how to fix this problem without violating the toppra.

**Comment by hungpham2511** [comment]
Hi @meihuiZhang,
- toppra can only account for dry fiction. If your problem has viscosity, the mathematical form becomes non-convex and the algorithm can't be used.
- See here for dry friction: https://github.com/hungpham2511/toppra/blob/24ab163c1999e04c02075919145351ae140f370e/toppra/constraint/joint_torque.py#L105

If you really need to account for viscosity, I can recommend the following approach:

- First, solve the problem with only dry friction;
- Compute viscous friction from the output, then treat it as another source of friction force;
- Solve the problem again with the new friction force.

There is no guarantee that this will work if the viscosity level is too high.
