### ISSUE TITLE
Remove useless scaling factor

### ISSUE THREAD

**Issue by hungpham2511** [hungpham2511/toppra#93]

**Comment by jmirabel** [comment]
I wasn't sure about the utility of this factor. Now I have my answer.

**Comment by hungpham2511** [comment]
Sorry I wasn't exactly clear with the issue. I was referring to this scaling factor:
https://github.com/hungpham2511/toppra/blob/24ab163c1999e04c02075919145351ae140f370e/toppra/constraint/linear_joint_velocity.py#L76
And not this:
https://github.com/hungpham2511/toppra/blob/24ab163c1999e04c02075919145351ae140f370e/toppra/solverwrapper/hot_qpoases_solverwrapper.py#L203

The latter one is quite important to handle some degenerate cases when x, u become very large.
